"""empty message

Revision ID: 2e2d931c9c5c
Revises: b0955c8bfc12
Create Date: 2023-02-24 09:25:45.925093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2d931c9c5c'
down_revision = 'b0955c8bfc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('author', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'author')
    # ### end Alembic commands ###
