"""empty message

Revision ID: 75a55553a55c
Revises: 812678f02220
Create Date: 2023-02-24 09:59:44.459503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a55553a55c'
down_revision = '812678f02220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
