"""empty message

Revision ID: 812678f02220
Revises: 2e2d931c9c5c
Create Date: 2023-02-24 09:28:42.964402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812678f02220'
down_revision = '2e2d931c9c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('author', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
