"""empty message

Revision ID: 87edf2358c8e
Revises: 75a55553a55c
Create Date: 2023-02-24 10:03:34.456724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87edf2358c8e'
down_revision = '75a55553a55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('authortest', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'authortest')
    # ### end Alembic commands ###
