"""empty message

Revision ID: 8fbced5afd51
Revises: 87edf2358c8e
Create Date: 2023-02-24 10:04:47.535821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbced5afd51'
down_revision = '87edf2358c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'authortest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('authortest', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
