"""favourite

Revision ID: b100a15422bd
Revises: c38f03f32907
Create Date: 2023-03-14 11:04:03.395424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b100a15422bd'
down_revision = 'c38f03f32907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourite_timestamp'), 'favourite', ['timestamp'], unique=False)
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reaction_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('reaction_like', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reaction_dislike', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reaction_heart', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reaction_laugh', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reaction_angry', sa.Integer(), nullable=True))
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('post', 'reaction_angry')
    op.drop_column('post', 'reaction_laugh')
    op.drop_column('post', 'reaction_heart')
    op.drop_column('post', 'reaction_dislike')
    op.drop_column('post', 'reaction_like')
    op.drop_table('reaction')
    op.drop_index(op.f('ix_favourite_timestamp'), table_name='favourite')
    op.drop_table('favourite')
    # ### end Alembic commands ###
