"""empty message

Revision ID: d88926382130
Revises: 8fbced5afd51
Create Date: 2023-02-24 10:14:53.520100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88926382130'
down_revision = '8fbced5afd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite', sa.Column('current_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favourite', 'current_id')
    # ### end Alembic commands ###
